-- Função auxiliar para updated_at (caso não exista)
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

-- Tabela de catálogo local dos cursos CEFIS
CREATE TABLE public.cefis_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INTEGER UNIQUE NOT NULL,
    title TEXT NOT NULL,
    subtitle TEXT,
    summary TEXT,
    keywords TEXT,
    goals TEXT,
    duration INTEGER,
    lesson_count INTEGER,
    average_rating FLOAT,
    categories TEXT,
    teacher_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    fts tsvector GENERATED ALWAYS AS (
        to_tsvector('portuguese',
            coalesce(title, '') || ' ' ||
            coalesce(subtitle, '') || ' ' ||
            coalesce(summary, '') || ' ' ||
            coalesce(keywords, '') || ' ' ||
            coalesce(goals, '')
        )
    ) STORED
);

CREATE INDEX cefis_catalog_fts_idx ON public.cefis_catalog USING GIN (fts);

GRANT SELECT ON public.cefis_catalog TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cefis_catalog TO authenticated;
GRANT ALL ON public.cefis_catalog TO service_role;

ALTER TABLE public.cefis_catalog ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on cefis_catalog"
ON public.cefis_catalog FOR SELECT USING (true);

CREATE TRIGGER update_cefis_catalog_updated_at
BEFORE UPDATE ON public.cefis_catalog
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();